site_name: Example Docs

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/ausfestivus/amplify-mkdocs-material"
edit_uri: "https://github.com/ausfestivus/amplify-mkdocs-material/edit/main/docs_sample"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "blue"
    accent: "blue"
  features:
    - tabs

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en